[package]
name = "cli_libvirt_backup_manager"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
chrono = { version = "0.4.42" }
libc = "0.2.175"
